### ISSUE TITLE
tests(jester): the test case does not pass

### ISSUE THREAD

**Issue by pikulet** [r3ndd/BeyondMafia-Integration#229]
- I previously added `againOnFinished` to the jester and exe cards to allow them to joint win. #200 
- It caused the jester test case to fail, need to see how to fix it

**Comment by DrSharky** [comment]
It seems to be caused by the fact that the test checks whether the Jester can joint with the mafia, which is not possible. Adding `againOnFinished: true` to the WinWithMafia.js winCheck causes the joint to be successful, but it also causes many other issues. It appears there needs to be a better way for mafia to joint with independent roles?

**Comment by pikulet** [comment]
The original test case states that jester cannot win with mafia. I had changed it thinking that Jester could now win with mafia. If so, then we can change it back to "jester cannot win with mafia" #218

**Comment by DrSharky** [comment]
> The original test case states that jester cannot win with mafia. I had changed it thinking that Jester could now win with mafia. If so, then we can change it back to "jester cannot win with mafia" #218

Yes, that's the part of the case that fails. If you weren't already aware, when you run the test, it should tell you which assertion didn't work if it fails. I.E.: (2) for the Jester tests.
