### ISSUE TITLE
bug(disguiser): Leaving as dead disguiser target makes guiser leave

### ISSUE THREAD

**Issue by DrSharky** [r3ndd/BeyondMafia-Integration#497]
Leaving the game as the dead target of the disguiser forces the disguiser to leave the game as well.

**Comment by pikulet** [comment]
Is this intended though? If someone is already in another lobby then you would know that they are guised.

**Comment by DrSharky** [comment]
> Is this intended though? If someone is already in another lobby then you would know that they are guised.

I am quite sure that it is not intended. If it is, we should refactor the way this works. As it stands, forcing an alive and active user to leave the game unknowingly, should not be the intended solution.

**Comment by pikulet** [comment]
by [kala](https://beyondmafia.com/community/forums/thread/O1qvRHyzm)

Since I dont see a general thread for guiser bugs anywhere, I'll make one here.
You should post any guiser bugs you find in here too.

Guiser bug: https://beyondmafia.com/game/qiviH0Cjo

So I found this out, I guised n1 and then I left d1, spectators is enabled so I came back to spectate and I noticed I could still write. I got shot and died still on d1, I went to the GY and noticed there are now 2 dead guisers, I could talk as myself too.
D2 I got revived and I showed as guised sheriff from n1, D3 I guised someone else and I left and joined back again, I could write as if I hadnt. I could do it more than once. And once I voted and the game kept going as normal, I vegged.

**Comment by pikulet** [comment]
other guiser bugs (too many) #492 #210 #449
